<?php

namespace Proxies\__CG__\Services\ScolariteBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Eleve extends \Services\ScolariteBundle\Entity\Eleve implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCODE($cODE)
    {
        $this->__load();
        return parent::setCODE($cODE);
    }

    public function getCODE()
    {
        $this->__load();
        return parent::getCODE();
    }

    public function setNomEleve($nomEleve)
    {
        $this->__load();
        return parent::setNomEleve($nomEleve);
    }

    public function getNomEleve()
    {
        $this->__load();
        return parent::getNomEleve();
    }

    public function setEmailEleve($emailEleve)
    {
        $this->__load();
        return parent::setEmailEleve($emailEleve);
    }

    public function getEmailEleve()
    {
        $this->__load();
        return parent::getEmailEleve();
    }

    public function setPhotoEleve($photoEleve)
    {
        $this->__load();
        return parent::setPhotoEleve($photoEleve);
    }

    public function getPhotoEleve()
    {
        $this->__load();
        return parent::getPhotoEleve();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'cODE', 'nomEleve', 'emailEleve', 'photoEleve');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}